// Copyright Private Asylum LLC, 2026, All Rights Reserved.

#include "GantryExamplesLogCategories.h"

DEFINE_LOG_CATEGORY(LogGantryExamples);
DEFINE_LOG_CATEGORY(LogGTCore);
DEFINE_LOG_CATEGORY(LogGTWorld);
DEFINE_LOG_CATEGORY(LogGTPlayer);
DEFINE_LOG_CATEGORY(LogGTPawn);
DEFINE_LOG_CATEGORY(LogGTInput);
DEFINE_LOG_CATEGORY(LogGTUI);
DEFINE_LOG_CATEGORY(LogGTAI);
DEFINE_LOG_CATEGORY(LogGTNet);
DEFINE_LOG_CATEGORY(LogGTSave);
